env:
  global:
    - PACKAGE_VERSION="0.1.0"
matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.2.401
      before_install: cd bexpr.cs.lang
      solution: BExpr.sln
      install: dotnet restore BExpr.sln
      script: 
        - dotnet build BExpr.sln /p:Configuration=Release /p:Version=${PACKAGE_VERSION}-pre-$TRAVIS_BUILD_NUMBER /p:AssemblyVersion=${PACKAGE_VERSION}.$TRAVIS_BUILD_NUMBER
      deploy:
        - dotnet nuget push bin/Release/BExpr.Core.Lang.${PACKAGE_VERSION}-pre-${TRAVIS_BUILD_NUMBER}.nupkg -k $NUGET_API_KEY
        
